/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(BytesToSC16.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(edc09ffc08198b5d67fb2395c916285a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <grnet/BytesToSC16.h>
// pydoc.h is automatically generated in the build directory
#include <BytesToSC16_pydoc.h>

void bind_BytesToSC16(py::module& m)
{

    using BytesToSC16    = ::gr::grnet::BytesToSC16;


    py::class_<BytesToSC16, gr::sync_decimator,
        std::shared_ptr<BytesToSC16>>(m, "BytesToSC16", D(BytesToSC16))

        .def(py::init(&BytesToSC16::make),
           D(BytesToSC16,make)
        )
        



        ;




}








