/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ByteComplexDecimator.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(632c66ae5c1dfb96056dbf23a86ef3fe)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <grnet/ByteComplexDecimator.h>
// pydoc.h is automatically generated in the build directory
#include <ByteComplexDecimator_pydoc.h>

void bind_ByteComplexDecimator(py::module& m)
{

    using ByteComplexDecimator    = ::gr::grnet::ByteComplexDecimator;


    py::class_<ByteComplexDecimator, gr::sync_decimator,
        std::shared_ptr<ByteComplexDecimator>>(m, "ByteComplexDecimator", D(ByteComplexDecimator))

        .def(py::init(&ByteComplexDecimator::make),
           py::arg("decimation"),
           D(ByteComplexDecimator,make)
        )
        



        ;




}








