/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ComplexToInt16Bytes.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(38c2e1df1399033869bd45818b46488d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <grnet/ComplexToInt16Bytes.h>
// pydoc.h is automatically generated in the build directory
#include <ComplexToInt16Bytes_pydoc.h>

void bind_ComplexToInt16Bytes(py::module& m)
{

    using ComplexToInt16Bytes    = ::gr::grnet::ComplexToInt16Bytes;


    py::class_<ComplexToInt16Bytes, gr::sync_interpolator,
        std::shared_ptr<ComplexToInt16Bytes>>(m, "ComplexToInt16Bytes", D(ComplexToInt16Bytes))

        .def(py::init(&ComplexToInt16Bytes::make),
           D(ComplexToInt16Bytes,make)
        )
        



        ;




}








