/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ComplexToSigned8.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(82ccdebc71e6d262369ae6f665982c65)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <grnet/ComplexToSigned8.h>
// pydoc.h is automatically generated in the build directory
#include <ComplexToSigned8_pydoc.h>

void bind_ComplexToSigned8(py::module& m)
{

    using ComplexToSigned8    = ::gr::grnet::ComplexToSigned8;


    py::class_<ComplexToSigned8, gr::sync_interpolator,
        std::shared_ptr<ComplexToSigned8>>(m, "ComplexToSigned8", D(ComplexToSigned8))

        .def(py::init(&ComplexToSigned8::make),
           D(ComplexToSigned8,make)
        )
        



        ;




}








