/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(FifoBuffer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f9d49e878b7d1787cc9386fea7c2619e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <grnet/FifoBuffer.h>
// pydoc.h is automatically generated in the build directory
#include <FifoBuffer_pydoc.h>

void bind_FifoBuffer(py::module& m)
{

    using FifoBuffer    = ::gr::grnet::FifoBuffer;


    py::class_<FifoBuffer, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<FifoBuffer>>(m, "FifoBuffer", D(FifoBuffer))

        .def(py::init(&FifoBuffer::make),
           py::arg("itemsize"),
           py::arg("minQueueLength"),
           D(FifoBuffer,make)
        )
        



        ;




}








