/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(IShortToSC16.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(740d4c466242c49bd851ad7a9c14c0ff)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <grnet/IShortToSC16.h>
// pydoc.h is automatically generated in the build directory
#include <IShortToSC16_pydoc.h>

void bind_IShortToSC16(py::module& m)
{

    using IShortToSC16    = ::gr::grnet::IShortToSC16;


    py::class_<IShortToSC16, gr::sync_decimator,
        std::shared_ptr<IShortToSC16>>(m, "IShortToSC16", D(IShortToSC16))

        .def(py::init(&IShortToSC16::make),
           D(IShortToSC16,make)
        )
        



        ;




}








