/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(PCAPUDPSource.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6776eafd35ae4347ea7a461d42c569a7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <grnet/PCAPUDPSource.h>
// pydoc.h is automatically generated in the build directory
#include <PCAPUDPSource_pydoc.h>

void bind_PCAPUDPSource(py::module& m)
{

    using PCAPUDPSource    = ::gr::grnet::PCAPUDPSource;


    py::class_<PCAPUDPSource, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<PCAPUDPSource>>(m, "PCAPUDPSource", D(PCAPUDPSource))

        .def(py::init(&PCAPUDPSource::make),
           py::arg("itemsize"),
           py::arg("port"),
           py::arg("headerType"),
           py::arg("payloadsize"),
           py::arg("notifyMissed"),
           py::arg("filename"),
           py::arg("repeat"),
           D(PCAPUDPSource,make)
        )
        



        ;




}








