/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(SC16ToComplex.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8ecbca0ec74bc5a1fc7f3ab9504387cf)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <grnet/SC16ToComplex.h>
// pydoc.h is automatically generated in the build directory
#include <SC16ToComplex_pydoc.h>

void bind_SC16ToComplex(py::module& m)
{

    using SC16ToComplex    = ::gr::grnet::SC16ToComplex;


    py::class_<SC16ToComplex, gr::sync_decimator,
        std::shared_ptr<SC16ToComplex>>(m, "SC16ToComplex", D(SC16ToComplex))

        .def(py::init(&SC16ToComplex::make),
           D(SC16ToComplex,make)
        )
        



        ;




}








