/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(SC16ToIShort.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(30e536b279118b79c118f0d970f07017)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <grnet/SC16ToIShort.h>
// pydoc.h is automatically generated in the build directory
#include <SC16ToIShort_pydoc.h>

void bind_SC16ToIShort(py::module& m)
{

    using SC16ToIShort    = ::gr::grnet::SC16ToIShort;


    py::class_<SC16ToIShort, gr::sync_interpolator,
        std::shared_ptr<SC16ToIShort>>(m, "SC16ToIShort", D(SC16ToIShort))

        .def(py::init(&SC16ToIShort::make),
           D(SC16ToIShort,make)
        )
        



        ;




}








